set_property -dict {PACKAGE_PIN Y18 IOSTANDARD LVCMOS33} [get_ports sys_clk]
#set_property -dict {PACKAGE_PIN P4 IOSTANDARD LVCMOS33} [get_ports sw_clk]
set_property -dict {PACKAGE_PIN P20 IOSTANDARD LVCMOS33} [get_ports rst_n]
set_property -dict {PACKAGE_PIN C19 IOSTANDARD LVCMOS33} [get_ports {test}]


#set_property -dict {PACKAGE_PIN Y9 IOSTANDARD LVCMOS33} [get_ports sw_pc_ins]
#set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets sw_clk_IBUF]

#set_property -dict {PACKAGE_PIN E13 IOSTANDARD LVCMOS33} [get_ports {seg7_led[0]}]
#set_property -dict {PACKAGE_PIN C15 IOSTANDARD LVCMOS33} [get_ports {seg7_led[1]}]
#set_property -dict {PACKAGE_PIN C14 IOSTANDARD LVCMOS33} [get_ports {seg7_led[2]}]
#set_property -dict {PACKAGE_PIN E17 IOSTANDARD LVCMOS33} [get_ports {seg7_led[3]}]
#set_property -dict {PACKAGE_PIN F16 IOSTANDARD LVCMOS33} [get_ports {seg7_led[4]}]
#set_property -dict {PACKAGE_PIN F14 IOSTANDARD LVCMOS33} [get_ports {seg7_led[5]}]
#set_property -dict {PACKAGE_PIN F13 IOSTANDARD LVCMOS33} [get_ports {seg7_led[6]}]
#set_property -dict {PACKAGE_PIN F15 IOSTANDARD LVCMOS33} [get_ports {seg7_led[7]}]

#set_property -dict {PACKAGE_PIN A18 IOSTANDARD LVCMOS33} [get_ports {seg7_select[7]}]
#set_property -dict {PACKAGE_PIN A20 IOSTANDARD LVCMOS33} [get_ports {seg7_select[6]}]
#set_property -dict {PACKAGE_PIN B20 IOSTANDARD LVCMOS33} [get_ports {seg7_select[5]}]
#set_property -dict {PACKAGE_PIN E18 IOSTANDARD LVCMOS33} [get_ports {seg7_select[4]}]
#set_property -dict {PACKAGE_PIN F18 IOSTANDARD LVCMOS33} [get_ports {seg7_select[3]}]
#set_property -dict {PACKAGE_PIN D19 IOSTANDARD LVCMOS33} [get_ports {seg7_select[2]}]
#set_property -dict {PACKAGE_PIN E19 IOSTANDARD LVCMOS33} [get_ports {seg7_select[1]}]
#set_property -dict {PACKAGE_PIN C19 IOSTANDARD LVCMOS33} [get_ports {seg7_select[0]}]
